[package]
name = "flappy_rust"
version = "0.1.0"
authors = ["Markus <markusreynolds1989@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfml = "0.14.0"
rand = ""
